AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'

    # - 'test/**/*'
    # Style/FrozenStringLiteralComment:
    #   Enabled: false
      
      
      
      